# Generated by Django 4.1.7 on 2023-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('width', models.IntegerField(default=512)),
                ('height', models.IntegerField(default=512)),
                ('model', models.CharField(max_length=200)),
                ('number_of_samples', models.IntegerField(default=512)),
                ('seed', models.IntegerField(default=512)),
                ('num_outputs', models.IntegerField(default=1)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
