# Generated by Django 4.1.7 on 2023-02-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='call',
            name='prompt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
