# Generated by Django 4.1.7 on 2023-02-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_initial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='seed',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
