# Generated by Django 4.1.7 on 2023-02-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_generatedimage_alter_call_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='generatedImage',
            new_name='generated_image',
        ),
    ]
