# Generated by Django 4.1.7 on 2023-02-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_alter_call_initial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='generated_image',
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
            ],
        ),
    ]
