# Generated by Django 4.1.7 on 2023-02-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_remove_call_generated_image_generatedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='num_outputs',
            new_name='number_of_outputs',
        ),
    ]
